version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16  # PostgreSQL 16 + pgvector
    container_name: chatbot_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: chatbot_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  chat-api:
    build: ./chat-api
    container_name: chatbot_chat_api
    restart: always
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: postgresql://postgres:postgres@db:5432/chatbot
      ORDER_API_URL: http://order-api:9000/cancel
    ports:
      - "8001:8001"
    depends_on:
      - db
      - order-api

  order-api:
    build: ./order-api
    container_name: chatbot_order_api
    restart: always
    ports:
      - "9000:9000"

volumes:
  db_data: