apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secrets
  namespace: chatbot
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  openai-api-key: # base64 encode your OpenAI API key
  postgres-password: cG9zdGdyZXM= # postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-config
  namespace: chatbot
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/chatbot"
  ORDER_API_URL: "http://order-api-service:9000/cancel"
  CHAT_API_URL: "http://chat-api-service:8001"