apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: chatbot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi